### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mordover** [dbt-labs/stitch-utils#11]
Hi DBT Team,

I noticed some discrepancies in the documentation here. The github uses "relation" as the argument for coalesce_fields (which appears to be correct), while the DBT docs utilize "from". Additionally, they both state that the arguments for adapter.get_relation are (schema, table) but they seem to actually be (database, schema, table) based on this https://docs.getdbt.com/docs/adapter#section-get_relation.

Hope this was helpful, thanks!

**Comment by jtcohen6** [comment]
Hi @Mordover, I'm not sure I know which documentation you're referring to. I believe the latest versions of both the README [in this repo](https://github.com/fishtown-analytics/stitch-utils/issues/11) and [on the Hub site](https://hub.getdbt.com/fishtown-analytics/stitch_utils/latest/) refer to `relation` as the argument to the `coalesce_fields` macro.

Is there other dbt documentation you're referring to that still uses `from`?

**Comment by Mordover** [comment]
I must have been looking at an older version, sorry about that!

**Comment by jtcohen6** [comment]
All good :) appreciate the thought!
