### ISSUE TITLE
Add <column_name>__decimal column type to stitch_coalesce function

### ISSUE THREAD

**Issue by cnlee1702** [dbt-labs/stitch-utils#23]
### Describe the feature
We are using Stitch for our load and `stitch_coalesce` doesn't recognize `<column_name>__decimal`. We are currently using `stitch-utils` version `0.3.1`. 

### Describe alternatives you've considered
The current solution is to coalesce the `<column_name>__decimal` column with the `<column_name>` column produced by the `stitch_coalesce` function. 

For example:
```
with

source as (

   {{ stitch_utils.coalesce_fields(relation = source('schema_name','table_name')) }}

),

renamed as (

   select 
      *, -- columns renamed in actual model

   -- stitch_coalesce produced "quantity" from "quantity__double" and "quantity__bigint"
   coalesce(
      "quantity__decimal"::varchar,
      "quantity"::varchar 
   ) as quantity 

)

select * from renamed
```

### Additional context
Discovered using [NetSuite SuiteTalk](https://www.stitchdata.com/docs/integrations/saas/netsuite-suitetalk) Stitch integration.

### Are you interested in contributing this feature?
Happy to help with this feature request. Let me know what I can do to help contribute 👍

**Comment by jtcohen6** [comment]
@cnlee1702 Thanks for opening the issue! We'd love to have you contribute the fix :)

It should be as simple as adding `'decimal'` to this list:
https://github.com/dbt-labs/stitch-utils/blob/860322686f230f74564907228736a8c85a28cfca/macros/coalesce_fields.sql#L21
